import type { Product } from "./chatbot-tools";

/**
 * Local product database - fallback when Google Sheets is not configured.
 * Contains all 50 LDA Energija products with specs and image URLs.
 */
export const LOCAL_PRODUCTS: Product[] = [
  // ---- MODULIAI (20) ----
  {
    id: "SM-001",
    tipas: "Modulis",
    gamintojas: "JinkoSolar",
    modelis: "Tiger Neo N-type 440W",
    galia: 440,
    efektyvumas: 21.8,
    technologija: "N-type monokristalinis, bifacial",
    garantija_metu: 25,
    kaina_eur: 145,
    nuotrauka_url: "https://www.jinkosolar.com/uploads/Tiger%20Neo%20N-type%20Module.png",
    pastabos: "N-type monokristalinis, bifacial",
  },
  {
    id: "SM-002",
    tipas: "Modulis",
    gamintojas: "JinkoSolar",
    modelis: "Tiger Neo N-type 445W",
    galia: 445,
    efektyvumas: 22.0,
    technologija: "N-type monokristalinis, bifacial",
    garantija_metu: 25,
    kaina_eur: 150,
    nuotrauka_url: "https://www.jinkosolar.com/uploads/Tiger%20Neo%20N-type%20Module.png",
    pastabos: "N-type monokristalinis, bifacial, aukštesnis efektyvumas",
  },
  {
    id: "SM-003",
    tipas: "Modulis",
    gamintojas: "JinkoSolar",
    modelis: "Tiger Neo N-type 550W",
    galia: 550,
    efektyvumas: 21.3,
    technologija: "N-type monokristalinis",
    garantija_metu: 25,
    kaina_eur: 195,
    pastabos: "Didesnis modulis, tinka dideliems stogams",
  },
  {
    id: "SM-004",
    tipas: "Modulis",
    gamintojas: "JinkoSolar",
    modelis: "Tiger Neo N-type 580W",
    galia: 580,
    efektyvumas: 22.4,
    technologija: "N-type monokristalinis",
    garantija_metu: 25,
    kaina_eur: 210,
    pastabos: "Premium N-type, aukštas efektyvumas",
  },
  {
    id: "SM-005",
    tipas: "Modulis",
    gamintojas: "JA Solar",
    modelis: "JAM72S30-545",
    galia: 545,
    efektyvumas: 21.1,
    technologija: "MBB PERC",
    garantija_metu: 25,
    kaina_eur: 185,
    pastabos: "MBB PERC technologija, patikimas",
  },
  {
    id: "SM-006",
    tipas: "Modulis",
    gamintojas: "JA Solar",
    modelis: "JAM60S21-375",
    galia: 375,
    efektyvumas: 20.3,
    technologija: "PERC",
    garantija_metu: 25,
    kaina_eur: 130,
    pastabos: "Kompaktiškas modulis, tinka mažesniems stogams",
  },
  {
    id: "SM-007",
    tipas: "Modulis",
    gamintojas: "JA Solar",
    modelis: "JAM54S31-420",
    galia: 420,
    efektyvumas: 21.5,
    technologija: "N-type",
    garantija_metu: 25,
    kaina_eur: 155,
    pastabos: "Deep Blue 3.0, N-type",
  },
  {
    id: "SM-008",
    tipas: "Modulis",
    gamintojas: "JA Solar",
    modelis: "JAM72D40-580",
    galia: 580,
    efektyvumas: 22.5,
    technologija: "Bifacial dvipusis",
    garantija_metu: 30,
    kaina_eur: 220,
    pastabos: "Bifacial dvipusis, 30 metų garantija",
  },
  {
    id: "SM-009",
    tipas: "Modulis",
    gamintojas: "Longi",
    modelis: "Hi-MO 6 440W",
    galia: 440,
    efektyvumas: 22.0,
    technologija: "HPDC",
    garantija_metu: 25,
    kaina_eur: 155,
    pastabos: "HPDC technologija, anti-PID",
  },
  {
    id: "SM-010",
    tipas: "Modulis",
    gamintojas: "Longi",
    modelis: "Hi-MO 5 550W",
    galia: 550,
    efektyvumas: 21.3,
    technologija: "PERC",
    garantija_metu: 25,
    kaina_eur: 195,
    pastabos: "Didesnis formatas, geras efektyvumas",
  },
  {
    id: "SM-011",
    tipas: "Modulis",
    gamintojas: "Trina Solar",
    modelis: "Vertex S+ 445W",
    galia: 445,
    efektyvumas: 22.2,
    technologija: "N-type TOPCon",
    garantija_metu: 25,
    kaina_eur: 160,
    pastabos: "N-type TOPCon, aukštas efektyvumas",
  },
  {
    id: "SM-012",
    tipas: "Modulis",
    gamintojas: "Trina Solar",
    modelis: "Vertex S 400W",
    galia: 400,
    efektyvumas: 20.8,
    technologija: "PERC",
    garantija_metu: 25,
    kaina_eur: 135,
    pastabos: "Populiarus modelis, gera kaina",
  },
  {
    id: "SM-013",
    tipas: "Modulis",
    gamintojas: "Canadian Solar",
    modelis: "HiKu6 445W",
    galia: 445,
    efektyvumas: 21.8,
    technologija: "TOPCon N-type",
    garantija_metu: 25,
    kaina_eur: 150,
    pastabos: "TOPCon N-type, patikimas gamintojas",
  },
  {
    id: "SM-014",
    tipas: "Modulis",
    gamintojas: "Canadian Solar",
    modelis: "BiHiKu7 580W",
    galia: 580,
    efektyvumas: 22.3,
    technologija: "Bifacial",
    garantija_metu: 25,
    kaina_eur: 215,
    pastabos: "Bifacial, dideliam stogui ar žemei",
  },
  {
    id: "SM-015",
    tipas: "Modulis",
    gamintojas: "Risen",
    modelis: "Titan S 440W",
    galia: 440,
    efektyvumas: 21.8,
    garantija_metu: 25,
    kaina_eur: 140,
    pastabos: "Gera kainos ir kokybės santykis",
  },
  {
    id: "SM-016",
    tipas: "Modulis",
    gamintojas: "Risen",
    modelis: "Titan 550W",
    galia: 550,
    efektyvumas: 21.2,
    garantija_metu: 25,
    kaina_eur: 185,
    pastabos: "Didelis modulis, ekonomiškas",
  },
  {
    id: "SM-017",
    tipas: "Modulis",
    gamintojas: "DMEGC",
    modelis: "DM445M10-54HBB",
    galia: 445,
    efektyvumas: 22.0,
    technologija: "N-type",
    garantija_metu: 25,
    kaina_eur: 135,
    pastabos: "N-type, konkurencinga kaina",
  },
  {
    id: "SM-018",
    tipas: "Modulis",
    gamintojas: "Q Cells",
    modelis: "Q.PEAK DUO ML-G11 400W",
    galia: 400,
    efektyvumas: 20.6,
    technologija: "Q.ANTUM DUO Z",
    garantija_metu: 25,
    kaina_eur: 165,
    pastabos: "Vokiška kokybė, Q.ANTUM DUO Z",
  },
  {
    id: "SM-019",
    tipas: "Modulis",
    gamintojas: "Hyundai",
    modelis: "HiE-S445HG 445W",
    galia: 445,
    efektyvumas: 21.9,
    technologija: "PERC",
    garantija_metu: 25,
    kaina_eur: 148,
    pastabos: "Pietų Korėjos kokybė, PERC",
  },
  {
    id: "SM-020",
    tipas: "Modulis",
    gamintojas: "Astronergy",
    modelis: "ASTRO N5 440W",
    galia: 440,
    efektyvumas: 21.7,
    technologija: "N-type TOPCon",
    garantija_metu: 25,
    kaina_eur: 142,
    pastabos: "N-type TOPCon, gera garantija",
  },

  // ---- INVERTERIAI (15) ----
  {
    id: "INV-001",
    tipas: "Inverteris",
    gamintojas: "Sungrow",
    modelis: "SG3.0RT",
    galia: 3000,
    ac_galia_kw: 3,
    efektyvumas: 97.8,
    garantija_metu: 10,
    kaina_eur: 850,
    faziskumas: "3f",
    pastabos: "Trijų fazių, kompaktiškas",
  },
  {
    id: "INV-002",
    tipas: "Inverteris",
    gamintojas: "Sungrow",
    modelis: "SG5.0RT",
    galia: 5000,
    ac_galia_kw: 5,
    efektyvumas: 98.0,
    garantija_metu: 10,
    kaina_eur: 1050,
    faziskumas: "3f",
    pastabos: "Trijų fazių, populiariausias modelis",
  },
  {
    id: "INV-003",
    tipas: "Inverteris",
    gamintojas: "Sungrow",
    modelis: "SG8.0RT",
    galia: 8000,
    ac_galia_kw: 8,
    efektyvumas: 98.3,
    garantija_metu: 10,
    kaina_eur: 1350,
    faziskumas: "3f",
    pastabos: "Trijų fazių, vidutinei sistemai",
  },
  {
    id: "INV-004",
    tipas: "Inverteris",
    gamintojas: "Sungrow",
    modelis: "SG10RT",
    galia: 10000,
    ac_galia_kw: 10,
    efektyvumas: 98.4,
    garantija_metu: 10,
    kaina_eur: 1550,
    faziskumas: "3f",
    pastabos: "Trijų fazių, didelei sistemai",
  },
  {
    id: "INV-005",
    tipas: "Inverteris",
    gamintojas: "Sungrow",
    modelis: "SG15RT",
    galia: 15000,
    ac_galia_kw: 15,
    efektyvumas: 98.5,
    garantija_metu: 10,
    kaina_eur: 1950,
    faziskumas: "3f",
    pastabos: "Trijų fazių, komercinėms sistemoms",
  },
  {
    id: "INV-006",
    tipas: "Inverteris",
    gamintojas: "Huawei",
    modelis: "SUN2000-3KTL-M1",
    galia: 3000,
    ac_galia_kw: 3,
    efektyvumas: 98.0,
    garantija_metu: 10,
    kaina_eur: 900,
    faziskumas: "1f",
    pastabos: "Vienos fazės, optimizatorių palaikymas",
  },
  {
    id: "INV-007",
    tipas: "Inverteris",
    gamintojas: "Huawei",
    modelis: "SUN2000-6KTL-M1",
    galia: 6000,
    ac_galia_kw: 6,
    efektyvumas: 98.2,
    garantija_metu: 10,
    kaina_eur: 1200,
    faziskumas: "3f",
    pastabos: "Trijų fazių, AFCI apsauga",
  },
  {
    id: "INV-008",
    tipas: "Inverteris",
    gamintojas: "Huawei",
    modelis: "SUN2000-10KTL-M1",
    galia: 10000,
    ac_galia_kw: 10,
    efektyvumas: 98.4,
    garantija_metu: 10,
    kaina_eur: 1600,
    faziskumas: "3f",
    pastabos: "Trijų fazių, FusionSolar app",
  },
  {
    id: "INV-009",
    tipas: "Inverteris",
    gamintojas: "Fox ESS",
    modelis: "H3-5.0-E",
    galia: 5000,
    ac_galia_kw: 5,
    efektyvumas: 97.5,
    garantija_metu: 10,
    kaina_eur: 1400,
    faziskumas: "3f",
    pastabos: "Hibridinis, baterijų palaikymas",
  },
  {
    id: "INV-010",
    tipas: "Inverteris",
    gamintojas: "Fox ESS",
    modelis: "H3-8.0-E",
    galia: 8000,
    ac_galia_kw: 8,
    efektyvumas: 97.8,
    garantija_metu: 10,
    kaina_eur: 1750,
    faziskumas: "3f",
    pastabos: "Hibridinis, trijų fazių",
  },
  {
    id: "INV-011",
    tipas: "Inverteris",
    gamintojas: "Fox ESS",
    modelis: "H3-12.0-E",
    galia: 12000,
    ac_galia_kw: 12,
    efektyvumas: 98.0,
    garantija_metu: 10,
    kaina_eur: 2100,
    faziskumas: "3f",
    pastabos: "Hibridinis, didelei sistemai su kaupikliu",
  },
  {
    id: "INV-012",
    tipas: "Inverteris",
    gamintojas: "Fronius",
    modelis: "Primo GEN24 5.0",
    galia: 5000,
    ac_galia_kw: 5,
    efektyvumas: 98.1,
    garantija_metu: 10,
    kaina_eur: 1300,
    faziskumas: "1f",
    pastabos: "Austriška kokybė, hibridinis",
  },
  {
    id: "INV-013",
    tipas: "Inverteris",
    gamintojas: "Fronius",
    modelis: "Symo GEN24 10.0",
    galia: 10000,
    ac_galia_kw: 10,
    efektyvumas: 98.2,
    garantija_metu: 10,
    kaina_eur: 1800,
    faziskumas: "3f",
    pastabos: "Trijų fazių hibridinis, premium",
  },
  {
    id: "INV-014",
    tipas: "Inverteris",
    gamintojas: "GoodWe",
    modelis: "GW5000-MS",
    galia: 5000,
    ac_galia_kw: 5,
    efektyvumas: 97.6,
    garantija_metu: 10,
    kaina_eur: 950,
    faziskumas: "1f",
    pastabos: "Vienos fazės, kompaktiškas",
  },
  {
    id: "INV-015",
    tipas: "Inverteris",
    gamintojas: "GoodWe",
    modelis: "GW10K-ET",
    galia: 10000,
    ac_galia_kw: 10,
    efektyvumas: 98.0,
    garantija_metu: 10,
    kaina_eur: 1450,
    faziskumas: "3f",
    pastabos: "Trijų fazių, ET hibridinis",
  },

  // ---- KAUPIKLIAI (10) ----
  {
    id: "BAT-001",
    tipas: "Kaupiklis",
    gamintojas: "Sungrow",
    modelis: "SBR064",
    galia: 0,
    talpa_kwh: 6.4,
    efektyvumas: 96,
    garantija_metu: 10,
    kaina_eur: 3200,
    pastabos: "LFP baterija, modulinė sistema",
  },
  {
    id: "BAT-002",
    tipas: "Kaupiklis",
    gamintojas: "Sungrow",
    modelis: "SBR096",
    galia: 0,
    talpa_kwh: 9.6,
    efektyvumas: 96,
    garantija_metu: 10,
    kaina_eur: 4500,
    pastabos: "LFP, 3 moduliai, plečiama",
  },
  {
    id: "BAT-003",
    tipas: "Kaupiklis",
    gamintojas: "Sungrow",
    modelis: "SBR128",
    galia: 0,
    talpa_kwh: 12.8,
    efektyvumas: 96,
    garantija_metu: 10,
    kaina_eur: 5800,
    pastabos: "LFP, 4 moduliai, namų ūkiui",
  },
  {
    id: "BAT-004",
    tipas: "Kaupiklis",
    gamintojas: "Sungrow",
    modelis: "SBR256",
    galia: 0,
    talpa_kwh: 25.6,
    efektyvumas: 96,
    garantija_metu: 10,
    kaina_eur: 10500,
    pastabos: "LFP, 8 moduliai, didelei sistemai",
  },
  {
    id: "BAT-005",
    tipas: "Kaupiklis",
    gamintojas: "Huawei",
    modelis: "LUNA2000-5-S0",
    galia: 0,
    talpa_kwh: 5.0,
    efektyvumas: 97,
    garantija_metu: 10,
    kaina_eur: 3000,
    pastabos: "LFP, modulinė, 1 modulis",
  },
  {
    id: "BAT-006",
    tipas: "Kaupiklis",
    gamintojas: "Huawei",
    modelis: "LUNA2000-10-S0",
    galia: 0,
    talpa_kwh: 10.0,
    efektyvumas: 97,
    garantija_metu: 10,
    kaina_eur: 5500,
    pastabos: "LFP, 2 moduliai, optimali talpa",
  },
  {
    id: "BAT-007",
    tipas: "Kaupiklis",
    gamintojas: "Huawei",
    modelis: "LUNA2000-15-S0",
    galia: 0,
    talpa_kwh: 15.0,
    efektyvumas: 97,
    garantija_metu: 10,
    kaina_eur: 7800,
    pastabos: "LFP, 3 moduliai, didelei sistemai",
  },
  {
    id: "BAT-008",
    tipas: "Kaupiklis",
    gamintojas: "Fox ESS",
    modelis: "ECS2900-H3",
    galia: 0,
    talpa_kwh: 5.76,
    efektyvumas: 95,
    garantija_metu: 10,
    kaina_eur: 2800,
    pastabos: "LFP, kompaktiškas, namams",
  },
  {
    id: "BAT-009",
    tipas: "Kaupiklis",
    gamintojas: "Fox ESS",
    modelis: "ECS4800-H5",
    galia: 0,
    talpa_kwh: 10.24,
    efektyvumas: 95,
    garantija_metu: 10,
    kaina_eur: 4800,
    pastabos: "LFP, dviguba talpa",
  },
  {
    id: "BAT-010",
    tipas: "Kaupiklis",
    gamintojas: "BYD",
    modelis: "HVS 5.1",
    galia: 0,
    talpa_kwh: 5.12,
    efektyvumas: 96,
    garantija_metu: 10,
    kaina_eur: 3100,
    pastabos: "Premium LFP, modulinė sistema",
  },

  // ---- EV STOTELĖS (5) ----
  {
    id: "EV-001",
    tipas: "EV stotele",
    gamintojas: "ABB",
    modelis: "Terra AC W7-G5",
    galia: 7000,
    garantija_metu: 3,
    kaina_eur: 650,
    jungtis: "Type 2",
    pastabos: "7 kW AC įkrovimas, Type 2",
  },
  {
    id: "EV-002",
    tipas: "EV stotele",
    gamintojas: "ABB",
    modelis: "Terra AC W11-G5",
    galia: 11000,
    garantija_metu: 3,
    kaina_eur: 850,
    jungtis: "Type 2",
    pastabos: "11 kW AC įkrovimas, Type 2",
  },
  {
    id: "EV-003",
    tipas: "EV stotele",
    gamintojas: "ABB",
    modelis: "Terra AC W22-G5",
    galia: 22000,
    garantija_metu: 3,
    kaina_eur: 1350,
    jungtis: "Type 2",
    pastabos: "22 kW AC įkrovimas, trijų fazių",
  },
  {
    id: "EV-004",
    tipas: "EV stotele",
    gamintojas: "Easee",
    modelis: "Easee Home",
    galia: 22000,
    garantija_metu: 3,
    kaina_eur: 750,
    jungtis: "Type 2",
    smart_funkcijos: "WiFi, Bluetooth, app valdymas",
    pastabos: "7-22 kW reguliuojamas, kompaktiškas dizainas",
  },
  {
    id: "EV-005",
    tipas: "EV stotele",
    gamintojas: "Wallbox",
    modelis: "Pulsar Plus",
    galia: 22000,
    garantija_metu: 3,
    kaina_eur: 700,
    jungtis: "Type 2",
    smart_funkcijos: "WiFi, Bluetooth, app valdymas",
    pastabos: "7-22 kW, mažiausias rinkoje, app valdymas",
  },
];
